# Generated by Django 6.0.5 on 2026-06-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='paypal_email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
